apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.backend.name }}-secret
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: {{ .Values.backend.secret.datasourceUsername | quote }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.backend.secret.datasourcePassword | quote }}