apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.backend.name }}-config
data:
  SPRING_DATASOURCE_URL: {{ .Values.backend.config.datasourceUrl | quote }}
  SPRING_KAFKA_BOOTSTRAP_SERVERS: {{ .Values.backend.config.kafkaBootstrapServers | quote }}
  SPRING_AI_OLLAMA_BASE_URL: {{ .Values.backend.config.ollamaBaseUrl | quote }}
