server:
  port: 8080
  http2:
    enabled: true
  tomcat:
    max-keep-alive-requests: 1000
    keep-alive-timeout: 60000

spring:
  profiles:
    active: local
  docker:
    compose:
      enabled: false
  application:
    name: sovereignty-ai
  threads:
    virtual:
      enabled: true
  autoconfigure:
    exclude:
      - org.springframework.ai.vectorstore.pgvector.autoconfigure.PgVectorStoreAutoConfiguration

  jpa:
    hibernate:
      ddl-auto: validate

  ai:
    openai:
      api-key: ${OPENAI_API_KEY:dummy-key-for-local-runs}
    ollama:
      base-url: http://localhost:11434
      embedding:
        options:
          model: mxbai-embed-large
      chat:
        model: tinydolphin

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,loggers,threaddump,heapdump,jfr
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
  metrics:
    tags:
      application: sovereignty-ai
  tracing:
    sampling:
      probability: 1.0

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

